# Generated by Django 6.0.5 on 2026-05-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('dogum_tarihi', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sifre', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
            ],
        ),
    ]
