# Generated by Django 6.0.5 on 2026-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isletme_adi', models.CharField(max_length=200)),
                ('isletme_tipi', models.CharField(max_length=100)),
                ('is_tanimi', models.TextField()),
                ('kisi_sayisi', models.IntegerField()),
                ('baslangic_tarihi', models.DateTimeField()),
                ('bitis_tarihi', models.DateTimeField()),
                ('ucret', models.IntegerField()),
            ],
        ),
    ]
