# Generated by Django 6.0.5 on 2026-05-13 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='konum',
            field=models.CharField(default='Bilinmiyor', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kullanici',
            name='hesap_turu',
            field=models.CharField(choices=[('calisan', 'Çalışan'), ('isletme', 'İşletme')], default='calisan', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Calisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.IntegerField()),
                ('kilo', models.IntegerField()),
                ('cinsiyet', models.CharField(max_length=50)),
                ('meslekler', models.CharField(max_length=300)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='calisanlar/')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='Isletme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isletme_adi', models.CharField(max_length=200)),
                ('isletme_adresi', models.CharField(max_length=300)),
                ('isletme_tipi', models.CharField(max_length=100)),
                ('aranan_meslekler', models.CharField(max_length=300)),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.kullanici')),
            ],
        ),
    ]
