# Generated by Django 6.0.5 on 2026-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ilan_konum_kullanici_hesap_turu_calisan_isletme'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='cinsiyet',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='deneyim',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='pozisyon',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='sigorta',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='ulasim',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='yas_araligi',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ilan',
            name='yemek',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
