# Generated by Django 6.0.5 on 2026-05-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ilan_cinsiyet_ilan_deneyim_ilan_pozisyon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(default='Beklemede', max_length=30)),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ilan')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kullanici')),
            ],
        ),
    ]
