# Generated by Django 6.0.5 on 2026-05-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_basvuru'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='isletme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.isletme'),
        ),
    ]
