# Generated by Django 6.0.6 on 2026-06-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ilan_isletme'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='aktif_mi',
            field=models.BooleanField(default=True),
        ),
    ]
