# Generated by Django 6.0.6 on 2026-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ilan_aktif_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru',
            name='calisan_puanladi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basvuru',
            name='isletme_puanladi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calisan',
            name='ortalama_puan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='calisan',
            name='puan_sayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='isletme',
            name='ortalama_puan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='isletme',
            name='puan_sayisi',
            field=models.IntegerField(default=0),
        ),
    ]
